### ISSUE TITLE
Parsed text file output

### ISSUE THREAD

**Issue by bkmgit** [intel/stats-collect#1]
Might it be possible to in addition to an html page, provide a summary text file output?

**Comment by bkmgit** [comment]
Alternatively, could html output without javascript be an option?

**Comment by dedekind** [comment]
In my opinion, it would be useful to provide a text-only report. Just a text file with summary table (the table that includes median/max/min/etc) for every metric. I do not have time to work on this now, though.

**Comment by adamjhawley** [comment]
I agree that text-only could be beneficial. For the time being, reports generate summary table files with the name 'summary-table.txt' in report directories. These files contain all of the data used in summary tables.

Note: those files were not designed to be manually read on their own. However, they are still reasonably straightforward to interpret.

**Comment by dedekind** [comment]
If someone contributes the feature, great. Stats-collect team agrees that the feature would be useful, bot does not have time working on it right now. Contributions would be appreciated. Therefore, closing this issue.
